@startuml
class étudiant {
  numéro d'étudiant
nom 
prénom
date de naissance
}
class cours {
titre
code du module
}
class examen {
date
coefficient
}
class Note{
valeur
}
étudiant "1..*" -- "0..*" cours
examen -- "1" cours
étudiant "0..*" -- "1..*" examen
(étudiant, examen) . Note
class Enseignant {
nomEnseignant
prénomEnseigant
}
cours -- "1" Enseignant
@enduml
